[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mpkg"
version = "0.1.0"
description = "Simple Motion Planning Packages"
authors = [
  {name = "Logesh"}
]
dependencies = [
  "pin == 3.9.0",
  "meshcat",
]
requires-python = ">=3.10"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]